language: cpp
matrix:
    include:
        # - os: linux
        #   compiler: gcc
        # - os: linux
        #   env: DEBUILD=YES
        #   compiler: gcc
        - os: osx
          compiler: clang
sudo: required
dist: trusty
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/cpuinfo /proc/meminfo; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep cpu; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep mem; fi
    #- if [[ "$TRAVIS_REPO_SLUG" == "staticfox/bif" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then openssl aes-256-cbc -K $encrypted_da8de0aafbfc_key -iv $encrypted_da8de0aafbfc_iv -in .travis-github.ssh.enc -out ~/kvirc-github-key -d; fi
    #- export encrypted_da8de0aafbfc_key=no
    #- pwd
script:
    - |
            make || exit 1
            if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
            if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make install; fi
            ls -l

after_success:
    - |
          echo hi
          npm install -g appdmg
          appdmg dist/appdmg.json KVIrc.dmg
          ls -l
          cd dist
          ls -l
    - |
          if [ "$BUILD_LEADER" == "YES" ] && [ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ] && [ "$TRAVIS_REPO_SLUG" == "staticfox/bif" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
              echo "All builds passed!"
          else
              echo "Not leader"
          fi
# TODO: build .dmg on osx and upload it
