language: cpp
matrix:
  include:
  - os: osx
    compiler: clang
sudo: required
dist: trusty
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/cpuinfo /proc/meminfo; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep cpu; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep mem; fi
script:
- |
  make || exit 1
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make install; fi
  ls -l
after_success:
- |
  npm install -g appdmg
  appdmg dist/appdmg.json KVIrc.dmg
  shorthash=`printf "%s" "$TRAVIS_COMMIT" | dd bs=1 count=10 2>/dev/null`
  curl --ftp-create-dirs -T KVIrc.dmg -u $FTP_USER:$FTP_PASS ${FTP_HOST}KVIrc-dev-git-${shorthash}.dmg

- |
  if [ "$BUILD_LEADER" == "YES" ] && [ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ] && [ "$TRAVIS_REPO_SLUG" == "staticfox/bif" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "All builds passed!"
  else
      echo "Not leader"
  fi
env:
  global:
  - secure: ostGaj0F9r3HVEgImA8gNG15/eyYG6OWwnZj4juXvPtWac/5cEYHr0MumyFHW23fCc55w0cauasIHLJpgWUrJT4uPbnQDixsg2fYN6D3K0PU0zgjo/ZdkbXRyWf1ngF3B4QyjMOUej7skHM8l4lzMq+U1gjY5FgBEPIL89NzFQPEIHMECfxw46OzFSywjAa5uU9juguvDyMFhzUg61mjocvkilHtn4lIzQYk0+43nx54MIcWtAmZcD8Mwl5iM3YE+q+hXTn6A5LT6KwOPPOkV6CbRF304mzglzv4bRTeeKKCqYl7742NxqvMFVBgg2NjqluzYUjblgEUxE2HQYveHhOsVzur7bkMIe7Aj8ibrkNDRMZNlSGb2kDDgBm7JKihQUk0fEJpNDw0OhgmY5riafzMz1omryysdJnLuBJpuUIgIh6dj17gY8bxkOx8Iz8MOc8KWLuuwxzP/nhX9sZdxH/0Tq4z2zC6BWoTIQCZ+MohUpwfsE7Wj5GzYnwpZ5n1VgvMhVbcex7Wl+eK2fCdfGB8CA78BxuK2W38dkw3iko5pgvtVl6WdMG0aMuFznnBIlGHbm1T30gaJy6Np0BNPg53ujjyqiIPKN2WBmLGR+c2KNZewf1FE2IKGKJdO9NKIVURZxqjhXFwUVI7V7hPxWKGBFKjUpDeJ19krk1u6fw=
  - secure: HoppaatcjCbNL1MTSYwglaQnOZB8xRDJ+cghIuoN+g0AkNZtp4saKm7Yh7MRejcCDG3UltjFUyJ8chAShAYVFc+BTMRyLAcz9u/8HmHeI3prO4fqQQLWz2j+I5oUvQ7zK6rzSxgMJY1C7Rjaf3hlg9q0lIjBxvDBR/m8NDtLMJQmJAV40saOLA01sDh/dv51CbU7MLwGYKXvHU6HOtvVlWIecsOvSTjQpbMIOLrE7g+XQ+DHRo7w+Wl1I7ltB79zkU+QZXF22neAFFMmQuI5I/4mmEbjF4fKbHOhnckmCL4bD/ITYw1aa6QThEy62zs0KeB2MbwpN4I70czCOkhts/Fn4OJ8UIZO0mVRIj7yDLbrDMOCumMnwdG0RXvVaJoHZ9WjODO4V9Wg+/AHSxMt9GO5QpZCnpBnT++KV0SpD2o6rcpZJdHhHnBh6mQgTfxLjAkrvBKcD3mArADCLJM3OWdQyhE2OqQChjCQ20smhePYalj/+RnogNhD/J2WDDPvo2UQXY1el2G1LHa61UXew+i8+38amWZJex96A+r/E6AvasPpY84jfS2hynHC/J2uU/vklSK3pkEllV9gK/FmPEuoQ+I5AOvQuaQV/4YcWR6fQY7E2mgLpGWNWjZ0dnFEdUNkma04Vv3Vwx93kgjC1Dqd66VaOSm33E3erSqRD/4=
  - secure: sk8iZCS3eHJdi8eePVayDlm/Oo6YBagGvt4cKUnW5qYAxYALSYLoSuysDsFCwowh6TB7Fxl6t1YTvppTll+Wvb47JSNIpkirYlzFGSfvNOR6z3nbwUG4azb3JB6h0k/cTxEWOYwpMtshJCkvV7CKtP1+ZUpcIRoegSVYRcBC6m9PfppdUMr6/SuDJ/HT/JXYlTE2mxhqRRflmNbVDYsbrUBSWdl3Fjvi5mgaCwd3nLAPViE8dnTnp7l7HgjMTS81tp2NKtkSxV48d6jpJgXCWrsLwP3q7DL5Pns8yT81IWEaTTifHgAPHPEuOYFlsJ+PjloizNTZqL4ux0I241U6I0+XSCyLatfK43U0poV0Ohf52wK38EBNPRMiR0k06lFjQDIVDHEbKfq9ULR90TPbmqMWEn7jywlqoMhInl9grTqagZ4oYAAvFJvUIYQQ5rpkaQd+rYiXfAXm/VDeaSqLKmcNGHr3Wk0E7c0Pfm05r5DFQcCgDWYgsaIpnwzwzrAY5zxcW4UWCKJwq+Q07TQXSVvJYaCxlNo7XPielrEi4h4mClr3mwLnAD/ZhW03//BvQWZVqRi+CcuIPxqoC6xWeryJK2qFGiOGfNkjs78c8l6nQYxZM+C4ekl6jE+Krgux1xX/ZtxFNzWnYGCkcN8teP6Bw5sFXTgYKSXfFNrTtvI=
