language: cpp
matrix:
  include:
  - os: osx
    compiler: clang
sudo: required
dist: trusty
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/cpuinfo /proc/meminfo; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep cpu; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep mem; fi
script:
- |
  make || exit 1
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make install; fi
  ls -l
after_success:
- |
  npm install -g appdmg
  appdmg dist/appdmg.json KVIrc.dmg
  shorthash=`printf "%s" "$TRAVIS_COMMIT" | dd bs=1 count=10 2>/dev/null`
  curl --ftp-create-dirs -T KVIrc.dmg -u $FTP_USER:$FTP_PASS ${FTP_HOST}KVIrc-dev-git-${shorthash}.dmg

- |
  if [ "$BUILD_LEADER" == "YES" ] && [ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ] && [ "$TRAVIS_REPO_SLUG" == "staticfox/bif" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "All builds passed!"
  else
      echo "Not leader"
  fi
env:
  global:
  - secure: ostGaj0F9r3HVEgImA8gNG15/eyYG6OWwnZj4juXvPtWac/5cEYHr0MumyFHW23fCc55w0cauasIHLJpgWUrJT4uPbnQDixsg2fYN6D3K0PU0zgjo/ZdkbXRyWf1ngF3B4QyjMOUej7skHM8l4lzMq+U1gjY5FgBEPIL89NzFQPEIHMECfxw46OzFSywjAa5uU9juguvDyMFhzUg61mjocvkilHtn4lIzQYk0+43nx54MIcWtAmZcD8Mwl5iM3YE+q+hXTn6A5LT6KwOPPOkV6CbRF304mzglzv4bRTeeKKCqYl7742NxqvMFVBgg2NjqluzYUjblgEUxE2HQYveHhOsVzur7bkMIe7Aj8ibrkNDRMZNlSGb2kDDgBm7JKihQUk0fEJpNDw0OhgmY5riafzMz1omryysdJnLuBJpuUIgIh6dj17gY8bxkOx8Iz8MOc8KWLuuwxzP/nhX9sZdxH/0Tq4z2zC6BWoTIQCZ+MohUpwfsE7Wj5GzYnwpZ5n1VgvMhVbcex7Wl+eK2fCdfGB8CA78BxuK2W38dkw3iko5pgvtVl6WdMG0aMuFznnBIlGHbm1T30gaJy6Np0BNPg53ujjyqiIPKN2WBmLGR+c2KNZewf1FE2IKGKJdO9NKIVURZxqjhXFwUVI7V7hPxWKGBFKjUpDeJ19krk1u6fw=
  - secure: HoppaatcjCbNL1MTSYwglaQnOZB8xRDJ+cghIuoN+g0AkNZtp4saKm7Yh7MRejcCDG3UltjFUyJ8chAShAYVFc+BTMRyLAcz9u/8HmHeI3prO4fqQQLWz2j+I5oUvQ7zK6rzSxgMJY1C7Rjaf3hlg9q0lIjBxvDBR/m8NDtLMJQmJAV40saOLA01sDh/dv51CbU7MLwGYKXvHU6HOtvVlWIecsOvSTjQpbMIOLrE7g+XQ+DHRo7w+Wl1I7ltB79zkU+QZXF22neAFFMmQuI5I/4mmEbjF4fKbHOhnckmCL4bD/ITYw1aa6QThEy62zs0KeB2MbwpN4I70czCOkhts/Fn4OJ8UIZO0mVRIj7yDLbrDMOCumMnwdG0RXvVaJoHZ9WjODO4V9Wg+/AHSxMt9GO5QpZCnpBnT++KV0SpD2o6rcpZJdHhHnBh6mQgTfxLjAkrvBKcD3mArADCLJM3OWdQyhE2OqQChjCQ20smhePYalj/+RnogNhD/J2WDDPvo2UQXY1el2G1LHa61UXew+i8+38amWZJex96A+r/E6AvasPpY84jfS2hynHC/J2uU/vklSK3pkEllV9gK/FmPEuoQ+I5AOvQuaQV/4YcWR6fQY7E2mgLpGWNWjZ0dnFEdUNkma04Vv3Vwx93kgjC1Dqd66VaOSm33E3erSqRD/4=
    secure: hWiCdo0l+TRErxd2jCJrem37i8AtGR0H2h9HVeRDq9zbZ/FdMbLBNC7CeVo8e7vZloFHJCfFNzGsJzBHo8jhUlBSH0V/ctMk0fZTEgXFx61YRDW1W2rj/QX2zfgm9P37gwkM+gjEQcmgYKoDa2g2Qg3jVsh7o6fM2i/VZpu2CcVbsESYX/diWvRPVCGGeb60/17lHQ5v2ce79qjVzEQHn1t0GeRmXF4Z5Lat4GmEQcFmleDV4D+JC71WmdjpJcv4+hy+Nl+T6nGp2237goAPkNvbShfEglPUHnHcP3eiBKqZODzojY3t+xO9eAmaOPZ5OwS+GfxvRwlkzWuDww80I+gxEBudG6d9XFczRL8Pir+F79qLfL5nB0gXAhXe89ta3p936O0tW0+LlncLCy2qo7dYpaZqLq7cKurPHb+6RqNNr8VVStUSmg03deo3UuvULki5fr9z5JoqLy/zpL8NztDfdoZApYCnrL1T+lZJnJCuBSuFANa0OnN0RR+UbbDDH1QAz5Kza6Tap9hTHPViRLi/yJ3BbsBKfwxqlqlGfWOtDonYMnUQtyOlZGY/PjQpLthjPC3oXsD2u5gQwyA0lYQICz0QUcVTW8n0fcgFTfEi8LYBhyu0qKWOVUwKusc7qJyXJF7rt+92qk95GhoVujTDDX+SYd62wXQB+uAG9cs=
